<a href="https://colab.research.google.com/github/mjayashri/machine-learning-refresher/blob/main/numpy_refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [130]:
import numpy as np

In [131]:
python_list = [1, 2, 3]
numpy_array = np.array([1,2,3])

In [132]:
python_list, numpy_array

([1, 2, 3], array([1, 2, 3]))

In [133]:
type(python_list), type(numpy_array)

(list, numpy.ndarray)

### Numpy from Ojects

In [134]:
np.array(python_list)

array([1, 2, 3])

In [135]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [136]:
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
type(my_matrix)

list

In [138]:
type(np.array(my_matrix))


numpy.ndarray

### Built-inm methods to create arrays

In [139]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [140]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [141]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [142]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### linspace (evenly spaced numbers over interval)

In [143]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [144]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### Identit matrix (eye)

In [145]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random

### rand (random samples from uniform distribution)

In [146]:
np.random.rand(4)

array([0.01596625, 0.23089383, 0.24102547, 0.68326352])

In [147]:
np.random.rand(4,4)

array([[0.60999666, 0.83319491, 0.17336465, 0.39106061],
       [0.18223609, 0.75536141, 0.42515587, 0.20794166],
       [0.56770033, 0.03131329, 0.84228477, 0.44975413],
       [0.39515024, 0.92665887, 0.727272  , 0.32654077]])

### randn (random samples from normal distribution)

In [148]:
np.random.randn(5)

array([-0.23413696,  0.78553212,  2.65601009,  0.26348604,  1.64177112])

In [149]:
np.random.randn(3,3)

array([[ 0.4608163 ,  0.08592347, -1.50995728],
       [ 0.72150246, -0.84341992, -0.51332541],
       [-0.0435368 , -0.27530091, -1.56306679]])

### randint (random integer from low to high)

In [150]:
np.random.randint(1, 50)

11

In [151]:
np.random.randint(1,100,20)

array([81,  8, 35, 35, 33,  5, 41, 28,  7, 73, 72, 12, 34, 33, 48, 23, 62,
       88, 37, 99])

### Seed (set random state, so each time same random results will be reproduced)

In [152]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

In [153]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

### Numpy methods & attributes

In [154]:
arr = np.arange(30)
randarr = np.random.randint(0, 50, 20)

In [155]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [156]:
randarr

array([10, 10, 23, 35, 39, 23,  2, 21,  1, 23, 43, 29, 37,  1, 20, 32, 11,
       21, 43, 24])

### Reshape

In [157]:
arr.reshape(6, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [158]:
### max, min, argmin, argmax

In [159]:
randarr

array([10, 10, 23, 35, 39, 23,  2, 21,  1, 23, 43, 29, 37,  1, 20, 32, 11,
       21, 43, 24])

In [160]:
randarr.max()

43

In [161]:
randarr.min()

1

In [162]:
randarr.argmax()

10

In [163]:
randarr.argmin()

8

In [164]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [165]:
arr.shape

(30,)

In [166]:
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [167]:
arr.reshape(1,30).shape

(1, 30)

In [168]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [169]:
arr.reshape(30,1).shape

(30, 1)

### dtype

In [170]:
arr.dtype

dtype('int64')

In [171]:
arr_new = np.array([1.2, 3.4, 5.6])
arr_new.dtype

dtype('float64')

# Numpy indexing and selection

In [172]:
arr = np.arange(0,15)

In [173]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [174]:
arr[0]

0

In [175]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [176]:
arr[0:5] = 50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [177]:
arr = np.arange(0,20)

In [178]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [179]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [180]:
slice_of_arr[:] = 50

In [181]:
slice_of_arr

array([50, 50, 50, 50, 50])

In [182]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [183]:
arr_copy = arr.copy()
arr_copy[0:5] = 80
arr_copy

array([80, 80, 80, 80, 80,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [184]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Indexing 2D array

In [185]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
arr_2d[0]

array([1, 2, 3])

In [187]:
arr_2d[0][1]

2

In [188]:
# 2d slicing
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [189]:
arr_2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [190]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

# Conditional selection

In [191]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [192]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [193]:
bool_array = arr < 5

In [194]:
bool_array

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [195]:
arr[bool_array]

array([1, 2, 3, 4])

# NumPy Operations

In [196]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [198]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [199]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [200]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [201]:
arr ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

### Mathematical Operations

In [202]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [204]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [205]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [206]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [207]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

## Statistical Operations

In [208]:
arr = np.arange(0,11)

In [209]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
arr.sum()

55

In [211]:
arr.max()

10

In [212]:
arr.min()

0

In [213]:
arr.mean()

5.0

In [214]:
arr.var()

10.0

In [215]:
arr.std()

3.1622776601683795

### Axis Logic

In [216]:
arr_2d = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])

In [217]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [218]:
arr_2d.sum(axis=0)

array([13, 16, 19, 22])

In [219]:
arr_2d.sum(axis=1)

array([10, 22, 38])

In [220]:
arr_2d.shape

(3, 4)